# Generated by Django 4.0.1 on 2022-01-24 21:38

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the client.', max_length=50, verbose_name='Name')),
                ('phone', models.CharField(blank=True, max_length=14, null=True)),
                ('cell_phone', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('state', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DataPlanDavis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('reference', models.CharField(max_length=10)),
                ('state', models.BooleanField(default=True)),
                ('start_date', models.DateField()),
                ('expire', models.DateField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Davis data Plan',
                'verbose_name_plural': 'Davis data Plans',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('identification', models.CharField(blank=True, max_length=12, null=True)),
                ('phone', models.CharField(max_length=14)),
            ],
            options={
                'verbose_name': 'Engineer',
                'verbose_name_plural': 'Enginers',
                'ordering': ['first_name'],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Type the name of the project.', max_length=50, verbose_name='Name')),
                ('description', models.TextField(max_length=300, verbose_name='Description')),
                ('state', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('modifier_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Modifier user')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_intern', models.CharField(max_length=6, verbose_name='internal identification')),
                ('name', models.CharField(help_text='Enter the name of the client.', max_length=12, verbose_name='Name')),
                ('maintenance_frecuency_months', models.IntegerField(help_text='Enter the frequency of maintenance in months.', verbose_name='Maintenance frequency')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('system', models.CharField(choices=[('NA', 'N/A'), ('OAP', 'Oleoducto Araguaney - Porvenir'), ('PA', 'Poliducto Andino'), ('PO', 'Poliducto de Oriente'), ('OCC', 'Oleoducto Caño Limón - Coveñas'), ('PGC', 'Poliducto Galan - Chimitá'), ('PSM', 'Poliducto Salgar - Mansilla'), ('PSC', 'Poliducto Salgar - Cartago'), ('YB', 'Yumbo - Buenaventura'), ('MC', 'Medellín - Cartago'), ('SM', 'Sebastopol - Medellín'), ('OTA', 'OTA - Orito Tumaco'), ('OAP', 'Oleoducto Araguaney - Porvenir'), ('SGN', 'Salgar - Gualanday - Neiva')], default='NA', max_length=3)),
                ('owner_phone', models.CharField(blank=True, max_length=14, null=True)),
                ('state', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('client', models.ManyToManyField(to='kenobiapp.Client')),
                ('modifier_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Modifier user')),
                ('project', models.ManyToManyField(to='kenobiapp.Project')),
            ],
            options={
                'verbose_name': 'Station',
                'verbose_name_plural': 'Stations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('execution_date', models.DateField()),
                ('service_description', models.TextField(max_length=300)),
                ('observation', models.TextField(blank=True, max_length=300, null=True)),
                ('state', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kenobiapp.engineer')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kenobiapp.station')),
            ],
            options={
                'verbose_name': 'Service Order',
                'verbose_name_plural': 'Service orders',
                'ordering': ['-update_at'],
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_maintenance', models.CharField(choices=[('P', 'Preventive'), ('C', 'Corrective')], default='P', max_length=1)),
                ('next_maintenance', models.DateField(blank=True, null=True)),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kenobiapp.serviceorder')),
            ],
            options={
                'verbose_name': 'Maintenance',
                'verbose_name_plural': 'Maintenance',
                'ordering': ['-service_order'],
            },
        ),
        migrations.CreateModel(
            name='DavisStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('did', models.CharField(help_text='This code is located on the device', max_length=20, verbose_name='DID')),
                ('key', models.CharField(help_text='This code is located on the device', max_length=20, verbose_name='DID')),
                ('af', models.CharField(blank=True, help_text='This code is provided by the Infrastructure leader or the administrative area.', max_length=15, null=True, verbose_name='Código Activos Fijos')),
                ('state', models.BooleanField(default=True)),
                ('observation', models.TextField(max_length=300)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('modifier_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Modifier user')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kenobiapp.dataplandavis')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kenobiapp.station')),
            ],
            options={
                'verbose_name': 'Service Order',
                'verbose_name_plural': 'Service orders',
                'ordering': ['name'],
            },
        ),
    ]
